# Dockerfile.firestore
FROM node:22-alpine

WORKDIR /workspace

# Install Firebase CLI and bash
RUN npm install -g firebase-tools && apk add --no-cache bash openjdk11-jre openssl nginx

COPY firebase.json ./

EXPOSE 8081 4000

CMD ["firebase", "emulators:start", "--only", "firestore", "--project", "elkr-prod"]
